### Login
POST http://localhost:3000/kiruna/api/sessions
Content-Type: application/json

{
    "username": "user1",
    "password": "123456"
}

### Get current user
GET http://localhost:3000/kiruna/api/sessions/current

### Logout
DELETE http://localhost:3000/kiruna/api/sessions/current

### Create user
POST http://localhost:3000/kiruna/api/users
Content-Type: application/json

{
    "username": "user1",
    "password": "123456",
    "role": "Urban Planner"
}


### Create a new document
POST http://localhost:3000/kiruna/api/documents
Content-Type: application/json

{
    "title": "Document Title2",
    "desc": "Document Description",
    "scale": "1:1000",
    "issuance_date": "2023-10-01",
    "type": "Design",
    "language": "IT",
    "link": "http://example.com",
    "pages": "100",
    "stakeholders": ["LKAB"],
    "connections": [{"doc2": 1,"link_type": "direct consequence"}]
}

### Get all stakeholders
GET http://localhost:3000/kiruna/api/stakeholders

### Update document description
PUT http://localhost:3000/kiruna/api/documents/1/description
Content-Type: application/json

{
    "desc": "Updated Document Description"
}

### Get all stakeholders
GET http://localhost:3000/kiruna/api/stakeholders

### Get all scales
GET http://localhost:3000/kiruna/api/scales

### Get all types
GET http://localhost:3000/kiruna/api/types

### Get all languages
GET http://localhost:3000/kiruna/api/languages

### Get all links
GET http://localhost:3000/kiruna/api/linktypes

### Get all documents
GET http://localhost:3000/kiruna/api/documents