name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [client, server]
    name: "Check: ${{ matrix.check }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm run install-all
      - name: Run check
        run: npm run ${{ matrix.check }}:check
    
  tests:
    runs-on: ubuntu-latest
    name: "Run server tests"
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install server dependencies
        working-directory: ./server
        run: npm install
      - name: Run tests
        working-directory: ./server
        run: npm test

  client-build:
    runs-on: ubuntu-latest
    name: "Build client"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install client dependencies
        working-directory: ./client
        run: npm install
      - name: Build client
        working-directory: ./client
        run: npm run build
